repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.2
    hooks:
      - id: ruff-format
        args:
          - --check
        files: .
        types_or: [python, pyi, jupyter]
        language_version: python3.12
      - id: ruff
        files: .
        types_or: [python, pyi, jupyter]
        language_version: python3.12
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.377
    hooks:
    - id: pyright
      files: .
      language_version: python3.12
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        files: .
        language_version: python3.12
