name: "Checks"

on:
  pull_request:
    branches:
      - "main"
      - "develop"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: install
      run: |
        make dev_install
    - name: format
      run: |
        make test_format
    - name: pytest
      run: |
        make pytest
